/**
 * User-facing names for summarisers. The openai provider is LM Studio
 * speaking an OpenAI-compatible API — never OpenAI's cloud.
 */

export function humanizeModelName(model: string): string {
  const slug = model.split("/").pop() ?? model;
  return slug
    .replace(/:/g, "-")
    .split(/[-_]+/)
    .filter(Boolean)
    .map((token) => {
      if (/^\d+[a-z]+$/i.test(token) || /^[a-z]\d/i.test(token)) {
        return token.toUpperCase();
      }
      const split = token.match(/^([a-z]+)(\d.*)$/i);
      if (split) {
        return `${split[1].charAt(0).toUpperCase()}${split[1].slice(1)} ${split[2]}`;
      }
      return token.charAt(0).toUpperCase() + token.slice(1);
    })
    .join(" ");
}

export function hostLabel(providerId: string): string {
  switch (providerId) {
    case "openai":
    case "lmstudio":
    case "openai-compat":
      return "LM Studio";
    case "ollama":
      return "Ollama";
    case "rules":
    case "manual":
      return "Rules engine";
    case "authored":
      return "Hand-written";
    default:
      return "Local LLM";
  }
}

export function parseSource(source: string): { provider: string; model: string } {
  const colon = source.indexOf(":");
  if (colon === -1) return { provider: source, model: "" };
  return { provider: source.slice(0, colon), model: source.slice(colon + 1) };
}

/** Visible caption plus tooltip for how a brief item was produced. */
export function briefGeneratorLabel(source: string): { caption: string; title: string } {
  if (source === "rules") {
    return { caption: "Generated by rules engine", title: "Extractive rules engine" };
  }
  if (source === "authored") {
    return { caption: "Hand-written", title: "Hand-written brief" };
  }

  const { provider, model } = parseSource(source);
  const host = hostLabel(provider);
  const name = model ? humanizeModelName(model) : host;
  return {
    caption: `Generated by ${name}`,
    title: model ? `${host} · ${humanizeModelName(model)}` : host,
  };
}

export function providerDisplay(id: string, model?: string | null): string {
  const host = hostLabel(id);
  if (!model || id === "rules" || id === "authored") return host;
  return `${host} · ${humanizeModelName(model)}`;
}
